#!/usr/bin/env python3
# Generate CMake set() statements for the Ai-BS21_SDK target config.
# Reuses the SDK's TargetEnvironment (read-only) and emits a .cmake file.
import os
import sys

SDK, TARGET, OUT = sys.argv[1], sys.argv[2], sys.argv[3]
sys.path.append(os.path.join(SDK, 'build', 'script'))
sys.path.append(os.path.join(SDK, 'build', 'config'))
from enviroment import TargetEnvironment

env = TargetEnvironment(TARGET, extra_defines=['NO_BOOT_BACKUP'])
env.remove('ram_component', 'demo')
env.remove('ram_component', 'samples')
env.append('ram_component', 'app')
env.append('ram_component', 'sdk_compat')

if 'rom_sym_path' in env.config:
    env.config['rom_sym_path'] = env.config['rom_sym_path'].replace('<root>', SDK)
    if os.path.exists(env.config['rom_sym_path']):
        env.config['linkflags'].append('-Wl,--just-symbols=' + env.config['rom_sym_path'])
        env.config['linkflags'].extend(env.get('symlink_linkflags', cmake_type=False, default=[]))
        env.config['ccflags'].extend(env.get('symlink_ccflags', cmake_type=False, default=[]))
        env.config['defines'].append('ROM_SYMBOL_LINK')

with open(OUT, 'w') as f:
    f.write('# Auto-generated by gen-config.py. Do not edit.\n')
    for key in env.config:
        val = env.get(key)
        if val is None or val == '':
            continue
        f.write('set(%s "%s" CACHE INTERNAL "" FORCE)\n' % (key.upper(), val))
    f.write('set(CMAKE_TOOLCHAIN_FILE "%s")\n' % env.get_tool_chain())
